### ISSUE TITLE
S3 deploy creates files without everyone read access

### ISSUE THREAD

**Issue by fehwalker** [octopress/deploy#41]
Deploy works, but files deployed to S3 do not have permission to be read, which means you can't actually use them as a web site unless you otherwise change all the permissions first.

Need to add ':acl => :public_read' to file options before uploading, Could possibly also have a config option to keep permissions private if preferred (why? maybe someone wants it...).

I'll try a fix for this since I want it...

**Comment by parkr** [comment]
:+1:

Start [here in your investigation](https://github.com/octopress/deploy/blob/master/lib/octopress-deploy/s3.rb#L65-L81). :)

**Comment by fehwalker** [comment]
This is fixed by commit 236980e
