### ISSUE TITLE
Boolean options in _deploy.yml don't seem to work

### ISSUE THREAD

**Issue by fehwalker** [octopress/deploy#42]
While looking at issue #41 I was trying to add a config file boolean to enable/disable the feature in _deploy.yml, and after a lot of testing I discovered the functionality is generally broken.

For example, if you set verbose to false in _deploy.yml it still prints verbose output.

**Comment by fehwalker** [comment]
The issue is that initialization of the verbose variable always results in it being true.

I believe the only relatively easy way to handle this is to have all booleans default to false unless explicitly set to true in the config, like the delete variable already is.

In the specific case of the verbose setting it's more consistent with general best practices anyway to have it default to off if not set. I'm going to put together a change to do this. I'll make sure the example initial config will still have it set to true.

**Comment by fehwalker** [comment]
I think this can be closed now.

**Comment by imathis** [comment]
Yep! You can try out 1.0.5 now and let me know if it goes well for you.

**Comment by fehwalker** [comment]
Yep, looks good, thanks!
