### ISSUE TITLE
S3 upload always deploys all files, even if unchanged

### ISSUE THREAD

**Issue by fehwalker** [octopress/deploy#44]
Would be nice if there was a way to only deploy changed files, not sure how feasible it is (I'll investigate).

**Comment by fehwalker** [comment]
I think the most consistent way to do this is to add a md5 sum to the S3 metadata for each file, and fetch and compare it for every file uploaded.

I think the logic is like this:
- for every file being uploaded try and fetch metadata using S3Object.head() (http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/S3/S3Object.html#head-instance_method)
- if md5 sum exists in metadata and if equal to md5 sum for file then skip
- otherwise write file and md5 sum in metadata

Hopefully the head() request is not too slow...

**Comment by imathis** [comment]
I believe this has been closed by #44. Please let me know if you feel otherwise.
