### ISSUE TITLE
@exclude and @include can only be used once

### ISSUE THREAD

**Issue by jdfrens** [octopress/deploy#52]
The `rsync` command allows multiple uses of `--exclude` and `--include`, but the `_deploy.yml` only accepts one filename for `exclude:` and for `include:`.

Something like this should work:

```ruby
Array(@exclude).each { |e| cmd << " --exclude #{e}" }
```

This works when `@exclude` is `nil`, a single value, or an entire array.

I'd try this myself, but I fought for way too long this morning with bundler to use my version of this gem instead of the official one, and bundler won.

**Comment by imathis** [comment]
Thanks for this. Ways to use your modification:

- You should be able to run `rake install` from you clone/fork of this project to install your version of this gem for testing. It will overwrite the matching version in your installed gems.
- If you don't want to override your, adding `gem 'octopress-deploy', path: 'path/to/your/gem'` to your Gemfile should work should work.
- Finally, you can run `bundle open octopress-deploy` to open the currently used gem source in your system editor, where you can add your modification and save the files.

Give it a try and let me know how it works for you. I'm happy to accept pull requests if that's convenient for you.

**Comment by jdfrens** [comment]
Setting the `path` in my Gemfile didn't work.  I pulled some other tricks that bundler suggested, but they didn't work either.

But the `rake install` solution worked fine for testing.  So PR #53 fixes this issue and issue #51.
