### ISSUE TITLE
"octopress build" doesn't seem to do anything

### ISSUE THREAD

**Issue by swgoldwood** [octopress/deploy#58]
Hi,

I'd like to deploy using rsync and I believe that the website needs to be rsynced from default site_dir (_site) to the remote path I specify in the _deploy.yaml. I can't find any documentation on how to build the app in the _site directory, but I have found online that some people are using "octopress build" to accomplish this (still just guessing).

When I run the build command, there is no output and it returns a success code, so I can only assume that "build" was a valid CLI command and execution was successful. But this doesn't seem to be doing anything, so when I actually deploy the blog I get the error: 

rsync: change_dir "XXXX/site//_site" failed: No such file or directory (2)

Any ideas?

**Comment by imathis** [comment]
There is no Octopress build command. I'm not sure why Mercenary doesn't properly return a failure. The Octopress CLI is documented here https://github.com/octopress/octopress. To build your site, use the `jekyll build` command. Octopress does not attempt to replace core features of Jekyll.

**Comment by swgoldwood** [comment]
Got it - Thanks! I'm coming to octopress as a ruby on rails guy and know nothing about jekyll. Might be worth putting something in the README.md of octopress main project to help losers like me :)
